// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mission struct {
	ID       int       `json:"ID"`
	Complete bool      `json:"Complete"`
	Targets  []*Target `json:"Targets"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type SpyCatInfo struct {
	ID               int      `json:"ID"`
	Name             string   `json:"Name"`
	YearOfExperience int32    `json:"YearOfExperience"`
	Breed            string   `json:"Breed"`
	Salary           int32    `json:"Salary"`
	Mission          *Mission `json:"Mission"`
}

type Target struct {
	ID       int    `json:"ID"`
	Name     string `json:"Name"`
	Country  string `json:"Country"`
	Notes    string `json:"Notes"`
	Complete bool   `json:"Complete"`
}

type Todo struct {
	ID   int    `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
