// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Email string `json:"email"`
	Age   int32  `json:"age"`
}

type Mission struct {
	ID       int       `json:"ID"`
	Complete bool      `json:"Complete"`
	Targets  []*Target `json:"Targets,omitempty"`
}

type Mutation struct {
}

type NewSpyCat struct {
	Name             string `json:"Name"`
	YearOfExperience int32  `json:"YearOfExperience"`
	Breed            string `json:"Breed"`
	Salary           int32  `json:"Salary"`
}

type Query struct {
}

type SpyCat struct {
	Name             string `json:"Name"`
	YearOfExperience int32  `json:"YearOfExperience"`
	Breed            string `json:"Breed"`
	Salary           int32  `json:"Salary"`
}

type SpyCatInfo struct {
	ID               int      `json:"ID"`
	Name             string   `json:"Name"`
	YearOfExperience int32    `json:"YearOfExperience"`
	Breed            string   `json:"Breed"`
	Salary           int32    `json:"Salary"`
	Mission          *Mission `json:"Mission,omitempty"`
}

type Target struct {
	ID       int    `json:"ID"`
	Name     string `json:"Name"`
	Country  string `json:"Country"`
	Notes    string `json:"Notes"`
	Complete bool   `json:"Complete"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
