basePath: /v1
definitions:
  main.CreateCatPayload:
    properties:
      breed:
        maxLength: 200
        type: string
      name:
        maxLength: 200
        type: string
      salary:
        minimum: 1
        type: integer
      year_of_experience:
        minimum: 1
        type: integer
    required:
    - breed
    - name
    - salary
    - year_of_experience
    type: object
  main.MissionPayload:
    properties:
      complete:
        type: boolean
      targets:
        items:
          $ref: '#/definitions/main.Target'
        maxItems: 3
        minItems: 1
        type: array
    required:
    - complete
    - targets
    type: object
  main.Target:
    properties:
      complete:
        type: boolean
      country:
        maxLength: 200
        minLength: 1
        type: string
      name:
        maxLength: 200
        minLength: 1
        type: string
      notes:
        maxLength: 255
        minLength: 1
        type: string
    required:
    - complete
    - country
    - name
    - notes
    type: object
  main.UpdateCatInfoPayload:
    properties:
      salary:
        minimum: 0
        type: integer
    required:
    - salary
    type: object
  main.UpdateNotesPayload:
    properties:
      notes:
        maxLength: 255
        minLength: 1
        type: string
    required:
    - notes
    type: object
  store.Cat:
    properties:
      breed:
        type: string
      id:
        type: integer
      name:
        type: string
      salary:
        type: integer
      year_of_experience:
        type: integer
    type: object
  store.Mission:
    properties:
      cat_id:
        type: integer
      completed:
        type: boolean
      id:
        type: integer
    type: object
  store.MissionWithMetadata:
    properties:
      cat:
        $ref: '#/definitions/store.Cat'
      mission:
        $ref: '#/definitions/store.Mission'
    type: object
  store.MissionWithTargets:
    properties:
      mission:
        $ref: '#/definitions/store.Mission'
      targets:
        items:
          $ref: '#/definitions/store.Target'
        type: array
    type: object
  store.Target:
    properties:
      completed:
        type: boolean
      country:
        type: string
      id:
        type: integer
      mission_id:
        type: integer
      name:
        type: string
      notes:
        type: string
    type: object
  store.UpdateTargetNote:
    properties:
      id:
        type: integer
      mission_id:
        type: integer
      notes:
        type: string
    type: object
  store.UpdateTargetStatus:
    properties:
      id:
        type: integer
      mission_id:
        type: integer
      status:
        type: boolean
    type: object
  store.UpdatedMission:
    properties:
      id:
        type: integer
      status:
        type: boolean
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Golang engineer test assessment - the Spy Cat Agency
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Golang engineer test assessment - the Spy Cat Agency
paths:
  /health:
    get:
      description: Health check
      produces:
      - application/json
      responses:
        "204":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Health check
      tags:
      - health
  /mission:
    post:
      consumes:
      - application/json
      description: Create new Mission
      parameters:
      - description: Mission payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.MissionPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/store.MissionWithTargets'
        "400":
          description: Bad Request
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create Mission
      tags:
      - mission
  /mission/{id}:
    delete:
      description: Delete mission by ID
      parameters:
      - description: mission ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema: {}
        "409":
          description: Conflict
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete mission
      tags:
      - mission
    get:
      description: Get one of mission by ID
      parameters:
      - description: Mission ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get one of mission
      tags:
      - mission
    patch:
      description: Update mission by ID
      parameters:
      - description: Mission ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.UpdatedMission'
        "400":
          description: Bad Request
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update mission
      tags:
      - mission
  /mission/{id}/cat/{cat_id}:
    patch:
      description: Add Spy Cat to Mission
      parameters:
      - description: Mission ID
        in: path
        name: id
        required: true
        type: integer
      - description: Cat ID
        in: path
        name: cat_id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Add Spy Cat to Mission
      tags:
      - mission
  /mission/{mission_id}/target:
    post:
      description: Add target to mission by mission_id and target_id
      parameters:
      - description: mission_id's ID
        in: path
        name: mission_id
        required: true
        type: integer
      - description: Target payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.Target'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Add target to mission
      tags:
      - target
  /mission/{mission_id}/target/{target_id}:
    delete:
      description: Delete target by mission id and target id
      parameters:
      - description: mission_id's ID
        in: path
        name: mission_id
        required: true
        type: integer
      - description: target_id's ID
        in: path
        name: target_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete target
      tags:
      - target
    patch:
      description: Update target's note  by ID
      parameters:
      - description: mission_id's ID
        in: path
        name: mission_id
        required: true
        type: integer
      - description: target_id's ID
        in: path
        name: target_id
        required: true
        type: integer
      - description: Update Target note
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.UpdateNotesPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.UpdateTargetNote'
        "400":
          description: Bad Request
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update target's note
      tags:
      - target
  /mission/{mission_id}/target_status/{target_id}:
    patch:
      description: Update target's status  by ID
      parameters:
      - description: mission_id's ID
        in: path
        name: mission_id
        required: true
        type: integer
      - description: target_id's ID
        in: path
        name: target_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.UpdateTargetStatus'
        "400":
          description: Bad Request
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update target's status
      tags:
      - target
  /mission/mission_list:
    get:
      description: List of missions
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/store.MissionWithMetadata'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: List of missions
      tags:
      - mission
  /ql/{id}:
    get:
      description: List of cats
      parameters:
      - description: Cat ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: List of cats
      tags:
      - spycat
  /spycat:
    get:
      consumes:
      - application/json
      description: Fetches spy cat list
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/store.Cat'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Fetches spy cat list
      tags:
      - spycat
    post:
      consumes:
      - application/json
      description: Create new spy cat
      parameters:
      - description: SpyCat payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.CreateCatPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/store.Cat'
        "400":
          description: Bad Request
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create spy cat
      tags:
      - spycat
  /spycat/{id}:
    delete:
      description: Delete spy cat by ID
      parameters:
      - description: Cat ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete spy cat
      tags:
      - spycat
    get:
      description: Get cat info by ID
      parameters:
      - description: Cat ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Cat'
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get cat info
      tags:
      - spycat
    patch:
      description: Update cat salary by ID
      parameters:
      - description: Cat ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update SpyCat payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.UpdateCatInfoPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Cat'
        "400":
          description: Bad Request
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update cat salary
      tags:
      - spycat
swagger: "2.0"
